### ISSUE TITLE
Instance: Test

### ISSUE THREAD

**Issue by vkt1414** [jcfr/MorphoCloudPortal#51]
### Cloud Computing Instance Flavor

m3.xl - General-purpose instance (32 CPUs, 125 GB RAM, no GPU)

### Description

Test

### ORCID

https://orcid.org/0000-0002-7901-4645

### Email

vamsikrishna1414@gmail.com

**Comment by jcfr** [comment]
Note that later this afternoon I will shutdown and delete the instance

**Comment by vkt1414** [comment]
It did work @jcfr! This is very cool!

I could not find it in my allocations probably because gmail instead of institutional email. Please go ahead and delete the instance whenever you can.
