### ISSUE TITLE
Instance: Chi's PW Week Test

### ISSUE THREAD

**Issue by chz31** [jcfr/MorphoCloudPortal#52]
### Cloud Computing Instance Flavor

g3.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)

### Description

Testing JetStream for using 3D Slicer and GPU. Project Week

### ORCID

0000-0002-0418-6354

### Email

chi.zhang@tamu.edu

**Comment by jcfr** [comment]
Note that later this afternoon I will shutdown and delete the instance
