### ISSUE TITLE
Instance: Emily, Cassandra's REU Student

### ISSUE THREAD

**Issue by climbergirl-prog** [jcfr/MorphoCloudPortal#62]
### Cloud Computing Instance Flavor

m3.xl - General-purpose instance (32 CPUs, 125 GB RAM, no GPU)

### Description

I am looking at poacher (Agonidae) scans with 3D Slicer for my REU research project. I am working with Dr. Cassandra Donatelli and Megan Vandenberg. 

### ORCID

0009-0009-2326-8759

### Email

delacrue@whitman.edu

**Comment by muratmaga** [comment]
you already have an instance. Only one instance per user is allowed.
