### ISSUE TITLE
Instance: Sims_Emma Parkside Student

### ISSUE THREAD

**Issue by littleprayingmantis** [jcfr/MorphoCloudPortal#86]
### Cloud Computing Instance Flavor

g3.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)

### Description

My name is Emma Sims and I am a student working with Dr. Noto and Dr. Taft on the Slicermorph grant at UW-Parkside. I will use this software to practice using Slicer technology.

### ORCID

0009-0004-3434-1548

### Email

emmasims1205@gmail.com

**Comment by muratmaga** [comment]
@littleprayingmantis please use the official portal. This is for testing only purposes.
http://instances.morpho.cloud
